//
//  CharactersRouter.swift
//  Swapi
//
//  Created by TuyenLe on 7/30/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoutingLogic
{
    func routeTo(from: UIViewController, to route: Router.Route, param: Any?)
}

class Router: NSObject, RoutingLogic {
    // MARK: Routing
    enum Route: String {
        case CharacterDetails
        case FilmDetails
        case PlanetDetails
        case SpecieDetails
        case StarshipDetails
        case VehicleDetails
    }

    func routeTo(from: UIViewController, to route: Router.Route, param: Any?) {
        var toVC: UIViewController = UIViewController()
        switch route {
        case .CharacterDetails:
            toVC = CharacterDetailsViewController()
            (toVC as! CharacterDetailsViewController).routeCharacterData = param as? People
            break
        case .FilmDetails:
            toVC = FilmDetailsViewController()
            (toVC as! FilmDetailsViewController).routeFilmData = param as? Film
            break
        case .PlanetDetails:
            toVC = PlanetDetailsViewController()
            (toVC as! PlanetDetailsViewController).routePlanetData = param as? Planet
            break
        case .SpecieDetails:
            toVC = SpecieDetailsViewController()
            (toVC as! SpecieDetailsViewController).routeSpecieData = param as? Specie
            break
        case .StarshipDetails:
            toVC = StarshipDetailsViewController()
            (toVC as! StarshipDetailsViewController).routeStarshipData = param as? Starship
            break
        case .VehicleDetails:
            toVC = VehicleDetailsViewController()
            (toVC as! VehicleDetailsViewController).routeVehiclepData = param as? Vehicle
            break
        }
        from.show(toVC, sender: nil)
    }
}
