//
//  CharactersRouter.swift
//  Swapi
//
//  Created by TuyenLe on 7/30/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RoutingLogic
{
    func routeTo(from: UIViewController, to route: Router.Route, param: Any?)
}

class Router: NSObject, RoutingLogic {
    // MARK: Routing
    enum Route: String {
        case CharacterDetails
        case FilmDetails
        case PlanetDetails
        case SpecieDetails
        case StarshipDetails
        case VehicleDetails
    }

    func routeTo(from: UIViewController, to route: Router.Route, param: Any?) {
        var toVC: UIViewController = UIViewController()
        switch route {
        case .CharacterDetails:
            toVC = from.storyboard!.instantiateViewController(withIdentifier: "CharacterDetailsViewController")
            (toVC as! CharacterDetailsViewController).characterIndex = param as? Int
            break
        case .FilmDetails:
            toVC = from.storyboard!.instantiateViewController(withIdentifier: "FilmDetailsViewController")
            (toVC as! FilmDetailsViewController).routeFilmData = param as? Film
            break
        case .PlanetDetails:
            toVC = from.storyboard!.instantiateViewController(withIdentifier: "PlanetDetailsViewController")
            (toVC as! PlanetDetailsViewController).routePlanetData = param as? Planet
            break
        case .SpecieDetails:
            toVC = from.storyboard!.instantiateViewController(withIdentifier: "SpecieDetailsViewController")
            (toVC as! SpecieDetailsViewController).routeSpecieData = param as? Specie
            break
        case .StarshipDetails:
            toVC = from.storyboard!.instantiateViewController(withIdentifier: "StarshipDetailsViewController")
            (toVC as! StarshipDetailsViewController).routeStarshipData = param as? Starship
            break
        case .VehicleDetails:
            toVC = from.storyboard!.instantiateViewController(withIdentifier: "VehicleDetailsViewController")
            (toVC as! VehicleDetailsViewController).routeVehiclepData = param as? Vehicle
            break
        }
        from.show(toVC, sender: nil)
    }
}
