//
//  SpeciesModels.swift
//  Swapi
//
//  Created by TuyenLe on 7/29/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Species
{
  // MARK: Use cases
  
  enum Fetch
  {
    struct Request
    {
        var sequence: Range<Int>
    }
    struct Response
    {
        var species: [Data?]
    }
    struct ViewModel
    {
        var species: [Specie]
    }
  }
}
