//
//  SpeciesInteractor.swift
//  Swapi
//
//  Created by TuyenLe on 7/29/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SpeciesBusinessLogic
{
  func getSpecies(request: Species.Fetch.Request)
}

protocol SpeciesDataStore
{

}

class SpeciesInteractor: SpeciesBusinessLogic, SpeciesDataStore
{
  var presenter: SpeciesPresentationLogic?
  var worker: SpeciesWorker? = SpeciesWorker(category: CategoryProtocolImplementation())
  
  // MARK: Fetch Species
  
  func getSpecies(request: Species.Fetch.Request)
  {
    worker?.getSpecies(sequence: request.sequence) { (datas: [Data?]) in
        let response = Species.Fetch.Response(species: datas)
        self.presenter?.presentSpecies(response: response)
    }
  }
}
