//
//  FilmsInteractor.swift
//  Swapi
//
//  Created by TuyenLe on 7/29/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FilmsBusinessLogic {
    func getFilms(request: Films.Fetch.Request)
}

protocol FilmsDataStore {
    var films: Data? { get }
}

class FilmsInteractor: FilmsBusinessLogic, FilmsDataStore {
    
    var presenter: FilmsPresentationLogic?
    var worker: FilmsWorker? = FilmsWorker(category: CategoryProtocolImplementation())
    
    var films: Data?
  
    // MARK: Get films
    func getFilms(request: Films.Fetch.Request) {
        worker?.getFilms { (films: Data?) -> Void in
            self.films = films
            self.presenter?.presentFilms(response: Films.Fetch.Response(films: films))
        }
    }
}
