//
//  FilmsWorker.swift
//  Swapi
//
//  Created by TuyenLe on 7/29/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FilmsWorker {
    var category: CategoryProtocol

    init(category: CategoryProtocol) {
        self.category = category
    }

    func getFilms(completion: @escaping (Data?) -> Void) {
        category.getFilms{ (films: () throws -> Data?) -> Void in
            do {
                let data = try films()
                completion(data)
            } catch let error {
                print(error)
                completion(nil)
            }
        }
    }
}
