//
//  ListInteractor.swift
//  Star Wars Index
//
//  Created by TuyenLe on 7/26/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersBusinessLogic {
    func getPeople(request: Characters.Fetch.Request)
}

protocol CharactersDataStore {
    var people: [Data?]? { get }
}

class CharactersInteractor: CharactersBusinessLogic, CharactersDataStore {

    var people: [Data?]?

    var presenter: CharactersPresentationLogic?
    var worker: CharactersWorker = CharactersWorker(category: CategoryProtocolImplementation())

    // MARK: Request StarWars API
    func getPeople(request: Characters.Fetch.Request) {
        worker.getPeople(sequence: request.sequence) { (people: [Data?]) in
            self.people = people
            self.presenter?.presentPeople(response: Characters.Fetch.Response(people: people))
        }
    }
}
