//
//  ListPresenter.swift
//  Star Wars Index
//
//  Created by TuyenLe on 7/26/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SwiftyJSON

protocol CharactersPresentationLogic {
    func presentPeople(response: Characters.Fetch.Response)
}

class CharactersPresenter: CharactersPresentationLogic {

    weak var viewController: CharactersDisplayLogic?
  
    // MARK: present data to ViewControllers
    
    func presentPeople(response: Characters.Fetch.Response) {
        let peopleDatas = response.people
        var peopleArray: [People] = []
        do {
            for peopleData in peopleDatas {
                if peopleData == nil { continue }

                let json = try JSON(data: peopleData!)

                for people in json["results"] {
                    peopleArray.append(People(name: people.1["name"].string!,
                                              height: people.1["height"].string!,
                                              mass: people.1["mass"].string!,
                                              hairColor: people.1["hair_color"].string!,
                                              skinColor: people.1["skin_color"].string!,
                                              eyeColor: people.1["eye_color"].string!,
                                              birthYear: people.1["birth_year"].string!,
                                              gender: people.1["gender"].string!,
                                              homeworld: nil,
                                              films: nil,
                                              vehicles: nil,
                                              starships: nil))
                }
            }
            viewController?.displayPeople(viewModel: Characters.Fetch.ViewModel(people: peopleArray))
        } catch let error {
            print("Error parsing characters Json: ", error)
        }
    }
}
