//
//  LaunchScreenModels.swift
//  Swapi
//
//  Created by TuyenLe on 7/30/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LaunchScreen
{
    // MARK: Use cases

    enum Fetch {
        struct Request {
            var sequence: Range<Int>
        }
        struct Response {
            struct People { var people: [Data?] }
            struct Films { var films: Data? }
            struct Planets { var planets: [Data?] }
            struct Species { var species: [Data?] }
            struct Starships { var starships: [Data?] }
            struct Vehicles { var vehicles: [Data?] }
        }
        struct ViewModel {
            struct Characters { var people: Dictionary<Int, People> }
            struct Films { var films: Dictionary<Int, Film> }
            struct Planets { var planets: Dictionary<Int, Planet> }
            struct Species { var species: Dictionary<Int, Specie> }
            struct Starships { var starships: Dictionary<Int, Starship> }
            struct Vehicles { var vehicles: Dictionary<Int, Vehicle> }
        }
    }
}
