//
//  LaunchScreenModels.swift
//  Swapi
//
//  Created by TuyenLe on 7/30/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LaunchScreen {
    // MARK: Use cases

    enum Fetch {
        // swiftlint:disable nesting
        struct Request {
            var sequence: Range<Int>
        }
        struct Response {
            struct Characters { var character: [Data?] }
            struct Films { var films: Data? }
            struct Planets { var planets: [Data?] }
            struct Species { var species: [Data?] }
            struct Starships { var starships: [Data?] }
            struct Vehicles { var vehicles: [Data?] }
        }
        struct ViewModel {
            // swiftlint:disable nesting
            struct Characters { var characters: [Int: Character] }
            struct Films { var films: [Int: Film] }
            struct Planets { var planets: [Int: Planet] }
            struct Species { var species: [Int: Specie] }
            struct Starships { var starships: [Int: Starship] }
            struct Vehicles { var vehicles: [Int: Vehicle] }
        }
    }
}
