//
//  LaunchScreenRouter.swift
//  Swapi
//
//  Created by TuyenLe on 7/30/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LaunchScreenRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LaunchScreenDataPassing
{
  var dataStore: LaunchScreenDataStore? { get }
}

class LaunchScreenRouter: NSObject, LaunchScreenRoutingLogic, LaunchScreenDataPassing
{
  weak var viewController: LaunchScreenViewController?
  var dataStore: LaunchScreenDataStore?
}
