//
//  PlanetsInteractor.swift
//  Swapi
//
//  Created by TuyenLe on 7/29/19.
//  Copyright (c) 2019 TuyenLe. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlanetsBusinessLogic
{
  func getPlanets(request: Planets.Fetch.Request)
}

protocol PlanetsDataStore
{
  //var name: String { get set }
    var planets: [Data?]? { get }
}

class PlanetsInteractor: PlanetsBusinessLogic, PlanetsDataStore
{
    var planets: [Data?]?
    
    var presenter: PlanetsPresentationLogic?
    var worker: PlanetsWorker? = PlanetsWorker(category: CategoryProtocolImplementation())
  
    // MARK: Do something
  
    func getPlanets(request: Planets.Fetch.Request)
    {
        worker?.getPlanets(sequence: request.sequence) { (planets: [Data?]) in
            let response = Planets.Fetch.Response(planets: planets)
            self.presenter?.presentPlanets(response: response)
        }
    }
}
